Lesson2
BubuntuClu/rubyrep pull request #1
Opened 2016-11-09 17:11 UTC by BubuntuClu

2016-11-09 19:34 UTC, vkurennov requested changes
Исправь замечания

2016-11-09 19:34 UTC, vkurennov commented on lesson2/task1.rb
> +    puts "#{month} got #{days}"
Если в теле условия всего одна строка, используй постфиксную форму записи.

2016-11-09 19:34 UTC, vkurennov commented on lesson2/task2.rb
> +  elem +=5;
Точки с запятой в руби не принято ставить, они ставятся только если несколько команд идет в одну строку.

2016-11-09 19:34 UTC, vkurennov commented on lesson2/task3.rb
> +while ( (new_arr[-1] + new_arr[-2]) <= 100) do
Внутренние скобки лишние, оператор + (точнее, метод) имеет больший приоритет, чем операторы сравнения, поэтому сначала будет сложение выполняться

2016-11-09 19:34 UTC, vkurennov commented on lesson2/task3.rb
> +  new_arr << (new_arr[-1] + new_arr[-2])
И тут скобки не нужны

2016-11-09 19:34 UTC, vkurennov commented on lesson2/task4.rb
> +  if (vowels.include?(letter) )
Используй постфиксный if и скобки в руби для условий не ставятся

2016-11-09 19:34 UTC, vkurennov commented on lesson2/task4.rb
> +  index+=1
чтобы вручную не считать индекс, используй метод each_with_index

2016-11-09 19:34 UTC, vkurennov commented on lesson2/task5.rb
> +noleap_months = {1 => 31, 2 => 28, 3 => 31, 4 => 30, 5 => 31, 6 => 30, 7 => 31, 8 => 31, 9 => 30,
Зачем тебе хеш, когда можно использовать массив с кол-вом месяцев. По номеру месяца легко получить индекс, просто отняв 1

2016-11-09 19:34 UTC, vkurennov commented on lesson2/task5.rb
> +leap_months = {1 => 31, 2 => 29, 3 => 31, 4 => 30, 5 => 31, 6 => 30, 7 => 31, 8 => 31, 9 => 30,
Зачем дублировать на 99% данные, когда можно поменять 1 элемент и только в случае выполнения определенного условия?

2016-11-09 19:34 UTC, vkurennov commented on lesson2/task5.rb
> +is_leap_year = (year % 4 == 0 && year % 400 == 0 )? true : false
Там еще нужно учитывать деление на 100

2016-11-09 19:34 UTC, vkurennov commented on lesson2/task5.rb
> +while (!months.include?(month)) do
у while не нужно ставить скобки

2016-11-09 19:34 UTC, vkurennov commented on lesson2/task5.rb
> +while (months[month] < day ) do
И тут скобки не нужны

2016-11-09 19:34 UTC, vkurennov commented on lesson2/task6.rb
> +  while (basket.include?(goods_name)) do
Убери скобки (внешние)

2016-11-09 19:34 UTC, vkurennov commented on lesson2/task6.rb
> +  break if goods_name.downcase == "STOP".downcase
А смысл писать строку большими буквами и вызывать downcase? Почему бы сразу маленькими не написать? вводимые данные, само собой, надо приводить к тому же регистру через downcase

2016-11-11 08:44 UTC, vkurennov requested changes

2016-11-11 08:44 UTC, vkurennov commented on lesson2/task3.rb
> +while ( new_arr[-1] + new_arr[-2] <= 100) do
И опять же: скобки у while не ставятся :-)

2016-11-11 08:44 UTC, vkurennov commented on lesson2/task5.rb
> +february = 29 if year % 4 == 0 && year % 100 != 0 || year % 400 == 0
А зачем ты снова проверяешь на високосность, если у тебя парой строк выше уже есть проверка (правда, неполная) и результат хранится в переменной is_leap_year.
Ну и сразу продолжу: зачем переменная is_leap_year типа boolean, когда можно сразу по выполнению условия установаить нужное значение дней в переменную february?

2016-11-11 15:19 UTC, BubuntuClu commented on lesson2/task3.rb
> +while ( new_arr[-1] + new_arr[-2] <= 100) do
Почему скобки надо опускать?
С ними ведь лучше видно условие, где оно начинается и где заканчивается.

2016-11-11 20:27 UTC, vkurennov approved these changes
Принято, но посмотри комментарий

2016-11-11 20:27 UTC, vkurennov commented on lesson2/task5.rb
> +if year % 4 == 0 && year % 100 != 0 || year % 400 == 0
Можно было применить тренарный оператор, как у тебя было ранее:

`february = (year % 4 == 0 && year % 100 != 0 || year % 400 == 0) ? 29: 28`

2016-11-12 08:40 UTC, merged