Lesson3
BubuntuClu/rubyrep pull request #2
Opened 2016-11-12 17:19 UTC by BubuntuClu

2016-11-12 19:42 UTC, vkurennov requested changes
Исправь замечания

2016-11-12 19:42 UTC, vkurennov commented on lesson3/Station.rb
> +  attr_accessor :next, :prev
А как у станции может быть только 1 предыдущая и следующая? Например, станция Москва, со скольки различных станций можно приехать в Москву и насколько уехать? Какая у Москвы начальная и конечная? Зависит от **маршрута** и от того, на какой станции в данный момент находтся **поезд**, идущий по этому маршруту.

2016-11-12 19:42 UTC, vkurennov commented on lesson3/Station.rb
> +    @trains.push(train)
Используй << для добавления в массив

2016-11-12 19:42 UTC, vkurennov commented on lesson3/Station.rb
> +  def start_train_to_next_station(train)
Это не ответсвтенность станции, это ответсвтенность поезда отправляться по маршруту.

2016-11-12 19:42 UTC, vkurennov commented on lesson3/Station.rb
> +      if self.next != nil
Поезд "знает", какая у него следующая станция на основании маршрута, станции на это "наплевать". Ее дело принять и отправить поезд, куда он отправляется, ей не важно.

2016-11-12 19:42 UTC, vkurennov commented on lesson3/Station.rb
> +  attr_reader :start_station
А почему только начальная станция? А если нужно будет вывести маршрут в виде "Начальная станция - конечная станция"?

2016-11-12 19:42 UTC, vkurennov commented on lesson3/Station.rb
> +  def add_station(station)
Опять же вся проблема в том, что у тебя станции почему-то связаны между собой, причем линейно, что неверно. Если это исправить, то операция добавления станции будет простой вставкой в массив

2016-11-12 19:42 UTC, vkurennov commented on lesson3/Station.rb
> +  def remove_station(station)
А тут будет просто удаление объекта из массива

2016-11-12 19:42 UTC, vkurennov commented on lesson3/Station.rb
> +        @stations.delete_at(@stations.index(station))
лучше использовать просто delete, он сразу принимает объект и удаляет его из массива

2016-11-12 19:42 UTC, vkurennov commented on lesson3/Station.rb
> +    self.speed = speed if speed > 0
1. Тут, наверное, лучше не просто присвавиать, а добавлять скорость, судя по названию метода
2. Как набрать начальную скорость, если при создании она равна нулю, а увеличивается только если скорость больше нуля?

2016-11-12 19:42 UTC, vkurennov commented on lesson3/Station.rb
> +    isMoved = self.current_station.start_train_to_next_station(self)
1. В руби принято называть переменные в snake_case, т.е. должно быть is_moved.
2. Вся логика по перемещению по станциям в маршруте должна быть как раз в этом классе и методе, а не у станции

2016-11-12 19:42 UTC, vkurennov commented on lesson3/Station.rb
> +  def show_stations
Раздели это на 3 метода: для текущей, следующей и предыдущей станций.

2016-11-13 07:48 UTC, BubuntuClu commented on lesson3/Station.rb
> +    self.speed = speed if speed > 0
Тут проверка задаваемой скорости, она должна быть больше 0, а не текущая скорость поезда

2016-11-13 07:49 UTC, BubuntuClu commented on lesson3/Station.rb
> +    @trains.push(train)
+

2016-11-13 09:42 UTC, vkurennov approved these changes
Принято, но исправь замечания перед выполнением следующего

2016-11-13 09:42 UTC, vkurennov commented on lesson3/Station.rb
> +    self.stations << station
По условию, конечная и начальная станция не меняются, т.е. новые станции **вставляются** в массив на предпоследнее место

2016-11-13 09:42 UTC, vkurennov commented on lesson3/Station.rb
> +    @route.stations[self.index_station].add_train(self)
а отукда возьмется начальное значение index_station? Ведь вызывав в первый раз этот метод, мы получим ошибку.

2016-11-13 09:42 UTC, vkurennov commented on lesson3/Station.rb
> +      if self.index_station == self.route.stations.size-1
Отступ в 2 пробела

2016-11-13 13:41 UTC, merged