Lesson9
BubuntuClu/rubyrep pull request #8
Opened 2016-11-22 18:40 UTC by BubuntuClu

Я в правильном направлении иду?
Не могу понять, почему в коде Route.rb вылазит ошибка валидации на существование "Field is not presence!".
Я не создаю станций и в самом роуте нет валидации на presence.

2016-11-23 09:25 UTC, BubuntuClu commented
Вроде разобрался. Просто общая переменная была на все классы. Надо сделать вот так

`   module ClassMethods
     attr_accessor :val_hash
     def validate(name, attr, *args)
       self.val_hash||= {}
       self.val_hash[name.to_sym] = [attr, args[0]]      
     end
 
    def get_hash
      self.val_hash
    end
  end`

В этом случае валидации проходят нормально

2016-11-23 09:44 UTC, vkurennov requested changes

2016-11-23 09:44 UTC, vkurennov commented on lesson9/modules/accessors.rb
> +          instance_variable_set("@#{arg}",0)
Почему 0? А если это строка? Да и зачем вообще устанавливать начальное значение?

2016-11-23 09:44 UTC, vkurennov commented on lesson9/modules/accessors.rb
> +        eval "@#{arg}_history+=[#{val}]"
Замени eval на instance_variable_set и т.п. eval старайся не сипользовать, это потенциальная дыра в безопасности, можно сделать инъекцию, т.к. eval выполнит все, что в него передать.

2016-11-23 09:44 UTC, vkurennov commented on lesson9/modules/accessors.rb
> +        instance_variable_set("@#{name}",0)
Опять не понятно почему инициализируем нулем и заче вообще инициализировать переменную?

2016-11-23 09:44 UTC, vkurennov commented on lesson9/modules/accessors.rb
> +      if val.class.to_s == class_name.to_s
А зачем сравнивать как строки? Почему просто классы не сравнить?

2016-11-23 09:44 UTC, vkurennov commented on lesson9/modules/validator.rb
> +    @@val_hash = {}
У тебя валидации в данном случае будут смешиваться со всеми классами, куда модуль подключен, и, например,  валидации станции будут применяться к поезду и наоборт. Тут нужно использовать инстанс-переменные уровня класса (да, в этом случае валидации не наследуются, но в задании про это и нет, хотя наследование сделать можно.)

2016-11-23 09:44 UTC, vkurennov commented on lesson9/modules/validator.rb
> +      @@val_hash[name.to_sym] = [attr, args[0]]
Валидации будут перезаписваться. Если в классе будет, скажем:

```
validate :name, :presence
validate :name, :format, /A-Z/
```

В этом случае, у поля останется только валидация на формат, а валидация на наличие поля "затрется"

2016-11-23 09:44 UTC, vkurennov commented on lesson9/modules/validator.rb
> +    define_method(:@@val_hash) do
Зачем такое  странное имя для метода и зачем вообще метод, где все статическое(имя, тело) задавать через define_method?

2016-11-23 09:44 UTC, vkurennov commented on lesson9/modules/validator.rb
> +        presence(k) if v[0].to_s == "presence"
Можно название метода динамически получить из названия валидатора и избежать if

2016-11-23 09:44 UTC, vkurennov commented on lesson9/modules/validator.rb
> +      raise "Field is not presence!" if instance_variable_get("@#{attr_name}").to_s.empty?
instance_variable_get можно перенести на уровень выше и передавать в метод уже значение, так во-первых избежим дублирования, а во-вторых, не придется каждый раз получать значение переменной, если валидаторов несколько

2016-11-23 14:36 UTC, BubuntuClu commented on lesson9/modules/accessors.rb
> +          instance_variable_set("@#{arg}",0)
+

2016-11-23 14:36 UTC, BubuntuClu commented on lesson9/modules/accessors.rb
> +        eval "@#{arg}_history+=[#{val}]"
+

2016-11-23 14:36 UTC, BubuntuClu commented on lesson9/modules/accessors.rb
> +        instance_variable_set("@#{name}",0)
+

2016-11-23 14:37 UTC, BubuntuClu commented on lesson9/modules/accessors.rb
> +      if val.class.to_s == class_name.to_s
+

2016-11-23 14:37 UTC, BubuntuClu commented on lesson9/modules/validator.rb
> +    @@val_hash = {}
+

2016-11-23 14:38 UTC, BubuntuClu commented on lesson9/modules/validator.rb
> +    define_method(:@@val_hash) do
+

2016-11-23 15:38 UTC, BubuntuClu commented on lesson9/modules/validator.rb
> +        presence(k) if v[0].to_s == "presence"
+

2016-11-23 15:38 UTC, BubuntuClu commented on lesson9/modules/validator.rb
> +      raise "Field is not presence!" if instance_variable_get("@#{attr_name}").to_s.empty?
+

2016-11-24 08:45 UTC, vkurennov requested changes

2016-11-24 08:45 UTC, vkurennov commented on lesson9/menu.rb
> +    self.stations = []
Инициалиацию лучше в конструктор вынести

2016-11-24 08:45 UTC, vkurennov commented on lesson9/modules/validator.rb
> +      self.val_hash[self.val_hash.size + 1] = [name.to_sym, attr, args[0]]
Зачем хранить индекс? Тогда уж массив использовать. Но лучше все же использовать хеш, где ключ - это имя атрибута, а вот значение - это массив всех валидаторов (т.е. массив массивов).

2016-11-24 08:45 UTC, vkurennov commented on lesson9/modules/validator.rb
> +    def get_hash
Так у тебя и так публичный attr_accessor есть, зачем тебе еще один геттер?

2016-11-24 08:45 UTC, vkurennov commented on lesson9/modules/validator.rb
> +      temp_hash = self.class.send(:get_hash)
Зачем send, если это публичный метод класса?

2016-11-24 15:13 UTC, BubuntuClu commented on lesson9/menu.rb
> +    self.stations = []
+

2016-11-24 15:17 UTC, BubuntuClu commented on lesson9/modules/validator.rb
> +    def get_hash
+

2016-11-24 15:17 UTC, BubuntuClu commented on lesson9/modules/validator.rb
> +      temp_hash = self.class.send(:get_hash)
+

2016-11-24 17:37 UTC, vkurennov requested changes
Упрости код

2016-11-24 17:37 UTC, vkurennov commented on lesson9/modules/validator.rb
> +      value = val_hash[name] ||= []
Какая-то сложная конструкция, тем более, что далее мы присваиваем `self.val_hash[name] = value`. Надо упростить. Если значения еще нет, добавляем пустой массив и потом в него добавляем массив параметров. У тебя так и происходит, но зачем тут переменная value? Можно сделать без нее.

2016-11-25 08:19 UTC, vkurennov approved these changes

2016-11-25 08:19 UTC, vkurennov commented on lesson9/modules/validator.rb
> +      self.val_hash[name].push([attr, args[0]])
Так гораздо лучше, но только используй << вместо push для добавления в массив

2016-11-25 08:19 UTC, vkurennov commented on lesson9/modules/validator.rb
> +        attr_args.each { |args| send(args[0], instance_variable_get("@#{attr_name}"), args[1]) }
Лучше вынести instance_variable_get из этого цикла, т.к. значение-то одно и то же, а ты его каждый раз заново получаешь для каждого валидатора.

2016-11-26 14:22 UTC, merged